import type { Project, Task, User } from "./types"

export const projectsData: Project[] = [
  {
    id: "1",
    title: "Website Redesign",
    description: "Redesign the company website to improve user experience.",
    students: ["Student 1", "Student 2"],
    category: "Web Development",
    progress: 100,
    startDate: "2023-01-01",
    endDate: "2023-06-01",
    status: "Completed",
  },
  {
    id: "2",
    title: "Mobile App Development",
    description: "Develop a mobile application for our services.",
    students: ["Student 3", "Student 4"],
    category: "Mobile Development",
    progress: 100,
    startDate: "2023-02-15",
    endDate: "2023-08-15",
    status: "Completed",
  },
  {
    id: "3",
    title: "Data Analysis Project",
    description: "Analyze data from the last quarter to find insights.",
    students: ["Student 5"],
    category: "Data Science",
    progress: 100,
    startDate: "2023-03-01",
    endDate: "2023-05-01",
    status: "Completed",
  },
  {
    id: "4",
    title: "Machine Learning Model",
    description: "Create a machine learning model for predictions.",
    students: ["Student 1", "Student 3"],
    category: "Machine Learning",
    progress: 100,
    startDate: "2023-04-01",
    endDate: "2023-09-01",
    status: "Completed",
  },
  {
    id: "5",
    title: "Machine Learning Model 2",
    description: "Create a machine learning model for predictions 2.",
    students: ["Student 1", "Student 3"],
    category: "Machine Learning",
    progress: 56,
    startDate: "2023-04-01",
    endDate: "2026-09-01",
    status: "In Progress",
  },
]

export const tasksData: Task[] = [
  {
    id: "1",
    project: "Website Redesign",
    name: "Design Homepage",
    description: "Create a responsive design for the homepage.",
    assignedStudent: "Ali Yaseen",
    status: "In Progress",
    dueDate: "4/22/2023",
  },
  {
    id: "2",
    project: "Website Redesign",
    name: "Develop API",
    description: "Set up the backend API for the project.",
    assignedStudent: "Braa Aeesh",
    status: "Completed",
    dueDate: "1/16/2023",
  },
  {
    id: "3",
    project: "Mobile App Development",
    name: "Write Documentation",
    description: "Document the project setup and usage.",
    assignedStudent: "Ibn Al-Jawzee",
    status: "Pending",
    dueDate: "3/15/2023",
  },
  {
    id: "4",
    project: "Mobile App Development",
    name: "Testing",
    description: "Conduct testing for all features.",
    assignedStudent: "Ibn Malik",
    status: "In Progress",
    dueDate: "11/29/2023",
  },
  {
    id: "5",
    project: "E-commerce Platform",
    name: "Deploy Application",
    description: "Deploy the application to the production server.",
    assignedStudent: "Ayman Outom",
    status: "Pending",
    dueDate: "3/24/2023",
  },
]

export const studentsData: User[] = [
  { id: "1", name: "Student 1", role: "Student", email: "student1@example.com" },
  { id: "2", name: "Student 2", role: "Student", email: "student2@example.com" },
  { id: "3", name: "Student 3", role: "Student", email: "student3@example.com" },
  { id: "4", name: "Student 4", role: "Student", email: "student4@example.com" },
  { id: "5", name: "Student 5", role: "Student", email: "student5@example.com" },
  { id: "6", name: "Ali Yaseen", role: "Student", email: "ali@example.com" },
  { id: "7", name: "Braa Aeesh", role: "Student", email: "braa@example.com" },
  { id: "8", name: "Ibn Al-Jawzee", role: "Student", email: "jawzee@example.com" },
  { id: "9", name: "Ibn Malik", role: "Student", email: "malik@example.com" },
  { id: "10", name: "Ayman Outom", role: "Student", email: "ayman@example.com" },
]

export const usersData: User[] = [
  ...studentsData,
  { id: "admin1", name: "Admin Ali", role: "Admin", email: "admin@example.com" },
]
